# Generated by Django 2.1.3 on 2018-12-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='accuracy',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='file',
            field=models.FileField(default='dummy.txt', upload_to='models/'),
        ),
    ]
